---

- name: Create a k8s namespace
  k8s:
    name: "{{consul_namespace}}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install helm chart for Consul
  helm:
    chart:
      name: consul
      source:
        type: repo
    state: present
    name: "{{consul_release_name}}"
    namespace: "{{consul_namespace}}"
