---
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place.
      command: >
        cp /tmp/linux-amd64/helm /usr/local/bin/helm
        creates=/usr/local/bin/helm

    - name: Add Stable Helm Repo.
      command: /usr/local/bin/helm repo add stable https://kubernetes-charts.storage.googleapis.com/
      register: helm_repo_results
      changed_when: False

    - name: List installed istable Helm charts.
      command: /usr/local/bin/helm search repo stable
      register: helm_list_results
      changed_when: False

