---
####################################################
# Developer: Sharad Dumoliya                       #
# Script name: main.yaml                           #
# Description:  Consul deployment                  #
# Version: 1.0.0                                   #
# Date of development: 27-Apr-2020                 #
####################################################
- hosts: k8s-master
  become: yes
  
  roles:
    - consul
  vars:
    task_type: ""