---

####################################################
# Developer: Sharad Dumoliya                       #
# Script name: main.yaml                           #
# Description:  Kubernetes deployment              #
# Version: 1.0.0                                   #
# Date of development: 26-May-2020                 #
####################################################

- hosts: "k8s-{{ node_type }}"

  roles:
    - k8s

