---
####################################################
# Developer: ESHADUM Sharad Dumoliya             #
# Script name: main.yml                            #
# Description: Kibana deployment tasks      #
# Version: 1.0.0                                   #
# Date of development:09-04-2020                   #
####################################################
- hosts: k8s-master
  become: yes

  roles:
    - kibana
  vars:
    task_type: ""