---

####################################################
# Developer: Sharad Dumoliya                       #
# Script name: main.yaml                           #
# Description:  Kubernetes Master node deployment  #
# Version: 1.0.0                                   #
# Date of development: 26-May-2020                 #
####################################################

- hosts: kubernetes-master-nodes
  become: yes

  roles:
    - master
