---

# Developer: Sharad Dumoliya
# Script name: openebs.yaml
# Description: Openebs Deployment
# Version: 1.0.0
# Date of development: 26-May-2020


- name: Install and start iSCSI client on worker nodes
  import_playbook: openebs_pre.yaml

- hosts: k8s-master
  become: yes

  roles:
    - openebs

