---
####################################################
# Developer: Sharad Dumoliya                       #
# Script name: main.yaml                           #
# Description: Prometheus Operator deployment      #
# Version: 1.0.0                                   #
# Date of development: 13-Apr-2020                 #
####################################################

- hosts: k8s-master
  become: yes

  roles:
    - prometheus_operator
  vars:
    task_type: ""