---
# Play book for install and configure Tools & application on K8S

- name: Installing Helm
  import_playbook: helm.yml

  #- name: Installing Cassandra on Kubernetes
  #import_playbook: cassandra.yml
