---
# Developer: Sharad Dumoliya
# Script name: main.yaml
# Description:  Istio deployment
# Version: 1.0.0
# Date of development: 03-Apr-2020

- name: Install Python Dependecies for helm
  pip:
    name:
      - pyhelm
      - grpcio
      - openshift
    extra_args: --user
    executable: /usr/bin/pip3


- name: Create a k8s namespace
  command: kubectl create namespace "{{istio_namespace}}"

- name: Install Istio Custom Resource Definitions
  command: /usr/local/bin/helm install --namespace "{{istio_namespace}}" istio-init istio.io/istio-init


- name: Wait for all Istio CRDs to be created
  command: kubectl -n "{{istio_namespace}}" wait --for=condition=complete job --all

- name: Install Istio’s core components
  command: /usr/local/bin/helm install --namespace "{{istio_namespace}}" istio istio.io/istio

