---
# Developer: Sharad Dumoliya
# Script name: main.yaml
# Description:  Istio deployment
# Version: 1.0.0
# Date of development: 03-Apr-2020

---
- name: Add Stable Helm Repo.
  command: /usr/local/bin/helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.5.1/charts/
  register: helm_repo_results
  changed_when: False

- name: List Helm charts.
  command: /usr/local/bin/helm search repo istio.io
  register: helm_list_results
  changed_when: False

- name: Install Python Dependecies for helm
  pip:
    name:
      - pyhelm
      - grpcio
      - openshift
    extra_args: --user
    executable: /usr/bin/pip3

- name: Create a k8s namespace
  k8s:
    name: "{{istio_namespace}}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install Istio Custom Resource Definitions
  command: /usr/local/bin/helm install --namespace "{{istio_namespace}}" "{{istio_init_release_name}}" istio.io/istio-init
  register: helm_istio_init_result
  failed_when: "'ERROR' in helm_istio_init_result.stderr"


- name: Wait for all Istio CRDs to be created
  command: kubectl -n "{{istio_namespace}}" wait --for=condition=complete job --all

- name: Install Istio’s core components
  command: /usr/local/bin/helm install --namespace "{{istio_namespace}}" "{{istio_release_name}}" istio.io/istio --values "{{istio_values}}"
  register: helm_istio_result
  failed_when: "'ERROR' in helm_istio_result.stderr"

- name: Change Kiali port to NodePort
  command: kubectl -n istio-system patch svc kiali --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'
