---
kibana_release_name: kibana
kibana_namespace: msra-monitoring
kibana_cluster_name: msra

kibana_image: docker.elastic.co/kibana/kibana:7.3.0
kibana_service: NodePort
kibana_nodePort: 30016

kibana_replica_count: 1
kibana_resources_limits_cpu: 1000m
kibana_resources_requests_cpu: 100m
#elasticsearch_url: "http://elasticsearch-service:9200"
#elasticsearch_url: "http://{{elasticsearch_ip.stdout}}:9200"
